-- solutions for the remaining queries
31.select * from Employee order by salary ASC;
32.select * from Employee order by salary DESC;
33.select * from Employee order by hire_date ASC;
34.select * from Employee order by department_id,salary;
35.select department_id,sum(salary) AS total_salary from Employee group by department_id order by total_salary;
36.select e.name,d.name from Employee e JOIN Department d on e.department_id = d.department_id;
37.select p.name,d.name from Project p JOIN Department d on p.department_id = d.department_id;
38.select e.name,p.name from Employee e JOIN Project p on e.project_id = p.project_id;
39.select e.name,d.name from Employee e LEFT JOIN Department d on e.department_id = d.department_id;
40.select d.name,e.name from Department d LEFT JOIN Employee e on d.department_id = e.department_id;
41.select * from Employee where project_id IS NULL;
42.select e.name,count(project_id) from Employee e JOIN Department d on e.department_id = d.department_id LEFT JOIN Project p on d.department_id = p.department_id GROUP BY e.name;
43.select d.* from Department d LEFT JOIN Employee e on d.department_id = e.department_id where e.emp_id IS NULL;
44.select e2.name from Employee e1 JOIN Employee e2 on e1.department_id = e2.department_id where e1.name = 'John Doe';
45.select d.name from Department d JOIN Employee e on d.department_id = e.department_id GROUP BY d.name ORDER BY d.name ORDER BY avg(e.salary) DESC limit 1;
46.select * from Employee where salary = (select max(salary) from Employee);
47.select * from Employee where salary > (select avg(salary) from Employee);
48.select max(salary) as second_highest_salary from Employee where salary < (select max(salary) from Employee);
49.select d.name,count(e.emp_id) AS total_employees from Department d JOIN Employee e on d.depatment_id = e.department_id GROUP BY d.name ORDER BY total_employees DESC limit 1;
50.select e.name,e.salary from Employee e where e.salary >(select avg(salary) from Employee where department_id = e.department_id);
51.select DISTINCT salary from Employee e1 where 2 = (select count(DISTINCT salary) from Employee e2 where e2.salary > e1..salary);
52.select * from Employee where age>ALL(select age from Employee where department_id = (select department_id from Department where name = 'HR'));
53.select d.name,avg(e.salary) AS avg_salary from Department d JOIN Employee e on d.department_id = e.department_id GROUP BY d.name having avg_salary  >55000;
54.select * from Employee where department_id from Project GROUP BY department_id having COUNT(project_id)>=2;
55.select * from Employee where hire_date =(select hire_date from Employee where name = 'Jane Smith');
56.select sum(salary) AS total_salary from Employee where YEAR(hire_date) =2020;
57.select d.name,avg(e.salary) AS avg_salary from Department d JOIN Employee e on d.department_id = e.department_id GROUP BY d.name ORDER BY avg_salary DESC;
58.select d.name from Department d JOIN Employee e on d.department_id = e.department_id GROUP BY d.name having COUNT(e.emp_id)>1 AND avg(e.salary) >55000;
59.select * from Employee where hire_date > CURRENT_DATE - INTERVAL 2 YEAR ORDER BY hire_date;
60.select department_id,count(*) AS total_employees,avg(salary) AS avg_salary from Employee GROUP BY department_id having count(*) > 2;
61.select e.name,e.salary from Employee e where e.salary > (select avg(salary) from Employee where department_id = e.department_id);
62.select name from Employee where hire_date = (select min(hire_date) from Employee);
63.select d.name,count(p.project_id) AS total_projects from Department d LEFT JOIN project p on d.department_id = p.department_id GROUP BY d.name ORDER BY total_projects DESC;
64.select e.name,e.department_id,e.salary from Employee where e.salary = (select MAX(salary) from Employee where department_id = e.department_id);
65.select e.name,e.salary from Employee e where e.age >(select avg(age) from Employee where department_id = e.department_id);
